### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mockonaa** [Saulagnefr/Projet-SI-2023#1]
Hello, c'est quand qu'il y aura un produit à peu près fonctionnel? même si ce n'est pas un livrable, au moins savoir à peu près à quoi ressemble le proto, ou même une idée du design final.

**Comment by Saulagnefr** [comment]
Pas maintenant, tu pourras attendre pour l'alpha du projet

**Comment by Saulagnefr** [comment]
finito
